name: CI

on:
  push:
    branches:
     - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: shearbook
          environment-file: environment.yml

      - name: Build Book
        shell: bash -l {0}
        run: |
          jupyter-book build shearbook

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: shearbook/_build/html
