name: CI

on:
  push:
    branches:
     - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: shearbook
          environment-file: environment.yml

      - name: Build Book
        shell: bash -l {0}
        run: |
          jupyter-book build shearbook

      - name: Deploy Development Pages
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: shearbook/_build/html
          publish_branch: dev-pages

      - name: Update Submodule on GH-Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          git submodule init
          git submodule update --remote --merge
          git submodule status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add develop
          git commit -m "updated dev-pages submodule"
          git push origin gh-pages
