name: CI

on:
  pull_request:
    branches:
     - develop
     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: shearbook
          environment-file: environment.yml

      - name: Build Book
        run: |
          conda activate shearbook
          conda info
          jupyter-book build shearbook
